apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: "2023-03-30T10:23:51Z"
  name: docker-credentials
  namespace: default
  resourceVersion: "147991"
  uid: f5bb4597-0b13-40f5-a0a8-8fe4fa97cc23
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJkYW52ZXJtb3IyMSIsInBhc3N3b3JkIjoiZGNrcl9wYXRfdlg2T2tOOG9rNUVNU09iUWMzcFlMYTlBYk00IiwiYXV0aCI6IlpHRnVkbVZ5Ylc5eU1qRTZaR05yY2w5d1lYUmZkbGcyVDJ0T09HOXJOVVZOVTA5aVVXTXpjRmxNWVRsQllrMDAifX19