kind: Secret
apiVersion: v1
metadata:
  name: github-secret
type: Opaque
stringData:
  .gitconfig: |
    [credential "https://github.com"]
      helper = store
  .git-credentials: |
    https://DanielVerano:<token>@github.com